# Generated by Django 5.1.1 on 2024-09-28 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.IntegerField(default=0)),
                ('exposureTime', models.IntegerField(default=0)),
                ('sustainTime', models.IntegerField(default=0)),
                ('overcomeTime', models.IntegerField(default=0)),
                ('lookAwayTime', models.IntegerField(default=0)),
                ('levelCleared', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
