# Generated by Django 4.1.13 on 2024-09-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameentry',
            name='exposureTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='lookAwayTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='overcomeTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='sustainTime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gameentry',
            name='totalTime',
            field=models.FloatField(default=0),
        ),
    ]
