# Generated by Django 4.1.13 on 2024-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_remove_gameentry_exposuretime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameentry',
            name='exposureTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='lookAwayTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='overcomeTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='sustainTime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gameentry',
            name='totalTime',
            field=models.FloatField(default=0),
        ),
    ]
